GUILess implementation
HSLU-BaumannWicki/BDA_FS19-RFIDTestFramework pull request #1
Opened 2019-04-19 12:51 UTC by KilnOfTheSecondFlame

Prepare for refactoring and tears 😅

2019-04-19 13:32 UTC, CryDeb requested changes

2019-04-19 13:32 UTC, CryDeb commented on src/main/kotlin/ApplicationStarter.kt
> +    val jsonFile = File(MultipleSequentialTestExecutor::class.java.getResource("package.json").path)
Allenfals neue Util klasse?

2019-04-19 13:32 UTC, CryDeb commented on src/main/kotlin/MultipleSequentialTestExecutor.kt
> +        // TODO Implement report generation
del TODOs

2019-04-19 13:32 UTC, CryDeb commented on src/main/kotlin/MultipleSequentialTestExecutor.kt
> +            testDataList.iterator().forEach { testData ->
if(!testDataList.stream().filter(data -> data.id == testId).empty()){
    executeTest(testId)
}

2019-04-19 13:32 UTC, CryDeb commented on src/main/kotlin/gui/GuiLess.kt
> +        messageIterator.forEach { message -> println(message) }
messageIterator.forEach(System.out::println)

2019-04-19 13:32 UTC, CryDeb commented on src/test/kotlin/gui/GuiLessTest.kt
> +        val guiObserver = GuiObserverStub()
// arrange

2019-04-19 13:32 UTC, CryDeb commented on src/test/kotlin/gui/GuiLessTest.kt
> +        guiLess.getUserInput(question)
// act

2019-04-19 13:32 UTC, CryDeb commented on src/test/kotlin/gui/GuiLessTest.kt
> +        assertEquals(answer, guiObserver.userMessages.last())
eigener Test

2019-04-19 13:32 UTC, CryDeb commented on src/test/kotlin/gui/GuiLessTest.kt
> +        assert(Pattern.compile(question).matcher(resultStream.toString()).find())
CleanCode?
Züge eines Integrationstest

2019-04-19 13:32 UTC, CryDeb commented on src/test/kotlin/gui/GuiLessTest.kt
> +        val guiObserver = GuiObserverStub()
assertThat(resultStream.toString(), contains(message))

2019-04-19 16:18 UTC, KilnOfTheSecondFlame commented
Thanks for all of the valuable input!
I tried to implement all of it, could you please recheck and give feedback?

2019-04-21 17:53 UTC, CryDeb approved these changes

2019-04-21 17:53 UTC, merged